spring:
  application:
    name: customer-service
  config:
    import: optional:configserver:http://config-server:8888?fail-fast=true&max-attempts=20&max-interval=3000&multiplier=1.2&initial-interval=1000