data:
  perfil: api-gateway
server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          #uri: http://localhost:8092
          uri: lb://customer-service
          predicates:
          - Path=/app-customer/**
          filters:
          - StripPrefix=1
        - id: product-service
          #uri: http://localhost:8091
          uri: lb://product-service
          predicates:
            - Path=/app-product/**
          filters:
            - StripPrefix=1
        - id: shopping-service
          #uri: http://localhost:8093
          uri: lb://shopping-service
          predicates:
            - Path=/app-shopping/**
          filters:
            - StripPrefix=1
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://eureka_user:eureka_password@localhost:8761/eureka