data:
  perfil: api-gateway-docker
server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/app-product/**
          filters:
            - StripPrefix=1
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/app-customer/**
          filters:
            - StripPrefix=1
        - id: shopping-service
          uri: lb://shopping-service
          predicates:
            - Path=/app-shopping/**
          filters:
            - StripPrefix=1
        - id: discovery-server-static
          uri: http://discovery-server:8761
          predicates:
            - Path=/app-eureka/**
          filters:
            - StripPrefix=1
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka_user:eureka_password@discovery-server:8761/eureka