data:
  name-profile: gateway-local-config
server:
  port: 8080
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          #uri: http://localhost:9092
          uri: lb://customer-service
          predicates:
            - Path=/app-customer/**
          filters:
            - StripPrefix=1
        - id: product-service
          #uri: http://localhost:9091
          uri: lb://product-service
          predicates:
            - Path=/app-product/**
          filters:
            - StripPrefix=1
        - id: shopping-service
          #uri: http://localhost:9093
          uri: lb://shopping-service
          predicates:
            - Path=/app-shopping/**
          filters:
            - StripPrefix=1
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://eureka_user:eureka_password@localhost:8761/eureka