data:
  name-profile: discovery-docker-config
server:
  port: 8761
eureka:
  instance:
    hostname: discovery-server
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
app:
  eureka:
    password: eureka_password
    username: eureka_user